# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  -
    id: "gpsinfo"
    binary: gpsinfo
    main: ./cmd/gpsinfo/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  -
    id: gpsinfo-binaries
    name_template: "gpsinfo-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - LICENSE.md
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
nfpms:
  -
    file_name_template: "gpsinfo_package_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Paepcke
    homepage: https://paepcke.de/gpsinfo
    maintainer: Michael Paepcke <git@paepcke.de>
    description: gpsinfo
    license: BSD 3-Clause
    formats:
      - deb
      - rpm
